In [2]:
import torch

In [17]:
N = 4
K = 3
vocab_size = 14
H = 128

In [18]:
pos1 = torch.randint(0, 10, size=(N, vocab_size))
pos1 = torch.repeat_interleave(pos1, K, 0)
pos1

tensor([[1, 4, 3, 4, 2, 7, 7, 8, 2, 8, 7, 9, 5, 2],
        [1, 4, 3, 4, 2, 7, 7, 8, 2, 8, 7, 9, 5, 2],
        [1, 4, 3, 4, 2, 7, 7, 8, 2, 8, 7, 9, 5, 2],
        [3, 9, 5, 4, 8, 6, 5, 5, 3, 4, 0, 0, 2, 3],
        [3, 9, 5, 4, 8, 6, 5, 5, 3, 4, 0, 0, 2, 3],
        [3, 9, 5, 4, 8, 6, 5, 5, 3, 4, 0, 0, 2, 3],
        [9, 6, 0, 9, 1, 0, 9, 6, 3, 5, 8, 4, 8, 3],
        [9, 6, 0, 9, 1, 0, 9, 6, 3, 5, 8, 4, 8, 3],
        [9, 6, 0, 9, 1, 0, 9, 6, 3, 5, 8, 4, 8, 3],
        [4, 3, 7, 8, 4, 5, 4, 8, 4, 3, 9, 7, 1, 8],
        [4, 3, 7, 8, 4, 5, 4, 8, 4, 3, 9, 7, 1, 8],
        [4, 3, 7, 8, 4, 5, 4, 8, 4, 3, 9, 7, 1, 8]])

In [24]:
test = pos1[::K]

In [25]:
test

tensor([[1, 4, 3, 4, 2, 7, 7, 8, 2, 8, 7, 9, 5, 2],
        [3, 9, 5, 4, 8, 6, 5, 5, 3, 4, 0, 0, 2, 3],
        [9, 6, 0, 9, 1, 0, 9, 6, 3, 5, 8, 4, 8, 3],
        [4, 3, 7, 8, 4, 5, 4, 8, 4, 3, 9, 7, 1, 8]])

In [30]:
lengths = torch.argmax((test == 2).int(), dim=-1)
lengths.masked_fill_(lengths == 0, 50)

tensor([ 4, 12, 50, 50])

In [31]:
lengths

tensor([ 4, 12, 50, 50])